import { Fleet } from '../types';

export const STOCK_FLEETS: Fleet[] = [
  {
    id: 'stock-airtags',
    name: 'Apple AirTags & Find My',
    enabled: true,
    matchAny: true,
    colorIndex: 0,
    kind: 'FINDER',
    builtIn: true,
    rules: [
      {
        kind: 'MANUFACTURER_DATA',
        dataPrefixHex: '121910',
        companyId: 0x004c,
        enabled: true,
      },
      {
        kind: 'SERVICE_UUID',
        text: 'FD6F',
        enabled: true,
      },
    ],
    notes: 'Apple offline location ecosystem and AirTag tracker tags.',
    attentionNote: '',
  },
  {
    id: 'stock-smarttag',
    name: 'Samsung Galaxy SmartTag',
    enabled: true,
    matchAny: true,
    colorIndex: 1,
    kind: 'FINDER',
    builtIn: true,
    rules: [
      {
        kind: 'SERVICE_UUID',
        text: 'FD5A',
        enabled: true,
      },
      {
        kind: 'NAME_CONTAINS',
        text: 'SmartTag',
        enabled: true,
      },
    ],
    notes: 'Samsung SmartThings Find beacon.',
    attentionNote: '',
  },
  {
    id: 'stock-tile',
    name: 'Tile Tracker',
    enabled: true,
    matchAny: true,
    colorIndex: 2,
    kind: 'FINDER',
    builtIn: true,
    rules: [
      {
        kind: 'SERVICE_UUID',
        text: 'FEED',
        enabled: true,
      },
      {
        kind: 'NAME_CONTAINS',
        text: 'Tile',
        enabled: true,
      },
      {
        kind: 'OUI',
        text: 'D4:36:39',
        enabled: true,
      },
    ],
    notes: 'Tile Bluetooth location beacon.',
    attentionNote: '',
  },
  {
    id: 'stock-flock',
    name: 'Flock Safety Falcon ALPR',
    enabled: true,
    matchAny: true,
    colorIndex: 2,
    kind: 'SURVEILLANCE',
    builtIn: true,
    rules: [
      {
        kind: 'OUI',
        text: 'B4:E6:2D',
        enabled: true,
      },
      {
        kind: 'NAME_CONTAINS',
        text: 'FS_Falcon',
        enabled: true,
      },
      {
        kind: 'NAME_CONTAINS',
        text: 'Flock',
        enabled: true,
      },
    ],
    notes: 'Flock Safety automated license plate reader (ALPR) camera installation.',
    attentionNote: 'Automated License Plate Reader (ALPR) camera system',
  },
  {
    id: 'stock-axon',
    name: 'Axon Body / Fleet Camera',
    enabled: true,
    matchAny: true,
    colorIndex: 2,
    kind: 'LAW_ENFORCEMENT',
    builtIn: true,
    rules: [
      {
        kind: 'OUI',
        text: '8C:85:90',
        enabled: true,
      },
      {
        kind: 'NAME_CONTAINS',
        text: 'AXON_',
        enabled: true,
      },
      {
        kind: 'SERVICE_UUID',
        text: 'FE57',
        enabled: true,
      },
    ],
    notes: 'Axon body-worn video and tactical in-car cameras.',
    attentionNote: 'Axon public safety body camera / fleet video',
  },
  {
    id: 'stock-opendroneid',
    name: 'FAA Remote ID Drone Broadcast',
    enabled: true,
    matchAny: true,
    colorIndex: 3,
    kind: 'DRONE',
    builtIn: true,
    rules: [
      {
        kind: 'SERVICE_UUID',
        text: 'FFFA',
        enabled: true,
      },
      {
        kind: 'NAME_CONTAINS',
        text: 'RID-',
        enabled: true,
      },
      {
        kind: 'VENDOR_IE_OUI',
        text: 'FA:0B:BC',
        enabled: true,
      },
    ],
    notes: 'ASTM F3411 / FAA Remote ID drone telemetry broadcast.',
    attentionNote: 'Active airborne drone / UAS Remote ID broadcast',
    decode: {
      source: 'serviceData',
      serviceUuid: 'FFFA',
      fields: [
        {
          id: 'uas_id',
          label: 'UAS Serial ID',
          offset: 1,
          length: 20,
          type: 'utf8',
          live: true,
        },
        {
          id: 'alt_m',
          label: 'Altitude',
          offset: 15,
          length: 2,
          type: 'u16',
          endian: 'le',
          scale: 0.5,
          unit: 'm',
          live: true,
        },
      ],
    },
  },
  {
    id: 'stock-flipper',
    name: 'Flipper Zero / Pentest Tool',
    enabled: true,
    matchAny: true,
    colorIndex: 4,
    kind: 'HACKING',
    builtIn: true,
    rules: [
      {
        kind: 'NAME_CONTAINS',
        text: 'Flipper',
        enabled: true,
      },
      {
        kind: 'SERVICE_UUID',
        text: '3082',
        enabled: true,
      },
    ],
    notes: 'Flipper Zero sub-GHz / RFID / Bluetooth pentesting device.',
    attentionNote: 'Sub-GHz / Bluetooth multi-tool hardware in proximity',
  },
  {
    id: 'stock-rayban-meta',
    name: 'Ray-Ban Meta Smart Glasses',
    enabled: true,
    matchAny: true,
    colorIndex: 5,
    kind: 'GLASSES',
    builtIn: true,
    rules: [
      {
        kind: 'NAME_CONTAINS',
        text: 'Ray-Ban Meta',
        enabled: true,
      },
      {
        kind: 'SERVICE_UUID',
        text: 'FE0C',
        enabled: true,
      },
    ],
    notes: 'Meta / Luxottica smart glasses with cameras and microphones.',
    attentionNote: 'Smart eyewear with video capture active',
  },
  {
    id: 'stock-tesla',
    name: 'Tesla Vehicle Key BLE',
    enabled: true,
    matchAny: true,
    colorIndex: 6,
    kind: 'VEHICLE',
    builtIn: true,
    rules: [
      {
        kind: 'NAME_CONTAINS',
        text: 'Tesla',
        enabled: true,
      },
      {
        kind: 'SERVICE_UUID',
        text: '6E400001-B5A3-F393-E0A9-E50E24DCCA9E',
        enabled: true,
      },
    ],
    notes: 'Tesla phone-as-key Bluetooth advertisement.',
    attentionNote: '',
  },
  {
    id: 'stock-meshtastic',
    name: 'Meshtastic Off-Grid Radio',
    enabled: true,
    matchAny: true,
    colorIndex: 7,
    kind: 'MESH',
    builtIn: true,
    rules: [
      {
        kind: 'NAME_CONTAINS',
        text: 'Meshtastic',
        enabled: true,
      },
      {
        kind: 'SERVICE_UUID',
        text: '6BA8CDD0-9FCE-4BEB-8A84-18EE5801BE24',
        enabled: true,
      },
    ],
    notes: 'LoRa mesh communicator node Bluetooth interface.',
    attentionNote: '',
  },
];
